#!/usr/bin/env bash
#
# Echoputer WPA crack-offload server installer (Rust).
#
# Sets up the PC side of the firmware's compute-offload (C) tier: installs hashcat,
# points you at a wordlist, pins the crack-server crate to the HOST target (the repo
# root forces xtensa, so we override it), builds it, and prints how to run it. The
# server is the std-only Rust service the Cardputer POSTs a captured .22000 to.
#
#
# Usage:  ./offload-install.sh
#
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
srv="$here/crack-server"
say()  { printf '\033[36m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[33m!! \033[0m %s\n' "$*" >&2; }

# ---- 1. hashcat ------------------------------------------------------------
if command -v hashcat >/dev/null 2>&1; then
  say "hashcat already installed: $(hashcat --version 2>/dev/null | head -1)"
else
  say "installing hashcat ..."
  if [[ "$(uname)" == "Darwin" ]]; then
    command -v brew >/dev/null 2>&1 || { warn "Homebrew not found — install from https://brew.sh then re-run"; exit 1; }
    brew install hashcat
  elif command -v apt-get >/dev/null 2>&1; then
    sudo apt-get update && sudo apt-get install -y hashcat
  elif command -v pacman >/dev/null 2>&1; then
    sudo pacman -S --noconfirm hashcat
  elif command -v dnf >/dev/null 2>&1; then
    sudo dnf install -y hashcat
  else
    warn "no known package manager — install hashcat manually: https://hashcat.net/hashcat/"
    exit 1
  fi
fi

# ---- 2. wordlist -----------------------------------------------------------
wl="$here/rockyou.txt"
if [[ -f "$wl" ]]; then
  say "wordlist present: $wl ($(wc -l < "$wl" | tr -d ' ') lines)"
else
  for c in /usr/share/wordlists/rockyou.txt; do
    [[ -f "$c" ]] && { say "found a system wordlist: $c"; wl="$c"; break; }
  done
  if [[ ! -f "$wl" ]]; then
    warn "no wordlist found. Grab one, e.g.:"
    warn "  curl -L -o '$here/rockyou.txt' https://github.com/brannondorsey/naive-hashcat/releases/download/data/rockyou.txt"
    warn "(or use the instructor's lab list)."
  fi
fi

# ---- 3. pin the crate to THIS host's target (repo root forces xtensa) ------
host="$(rustc -vV 2>/dev/null | sed -n 's/^host: //p')"
[[ -z "$host" ]] && host="aarch64-apple-darwin"
say "host target: $host"
mkdir -p "$srv/.cargo"
cat > "$srv/.cargo/config.toml" <<EOF
# Auto-generated by offload-install.sh. This is a HOST tool; the repo-root
# .cargo/config forces xtensa + a no_std build-std, so override for the host.
# Cargo JOINS \`build-std\` arrays (can't unset core/alloc), hence "std" is added
# and the host std is built from source via the esp toolchain's rust-src.
[build]
target = "$host"

[unstable]
build-std = ["std", "panic_unwind"]
EOF

# ---- 4. build --------------------------------------------------------------
say "building crack-server (first build compiles host std from source, ~30s) ..."
( cd "$srv" && cargo build --release )
bin="$srv/target/$host/release/crack-server"

# ---- 5. run instructions ---------------------------------------------------
say "done. start the server with:"
echo
echo "    '$bin' '$wl' 8080"
echo
say "then test it (pull HS22000.TXT off the Cardputer's SD):"
echo
echo "    curl -s --data-binary @HS22000.TXT http://localhost:8080/crack ; echo"
echo
say "the recovered passphrase comes back in the response body (empty = not in the wordlist)."
