//! wiki screen translations.
use super::Msg;

pub const WIFI_SCAN: Msg = ["Scans nearby Wi-Fi access points.\nLists SSID, RSSI signal, channel,\nand encryption type per AP.\nUse it to map the RF environment\nand spot open or weak networks.\nPassive recon - reads beacons only.\nDefense: secure all APs with\nWPA2/WPA3, not open or WEP.", "Yakindaki Wi-Fi noktalarini tarar.\nHer AP icin SSID, RSSI sinyal,\nkanal ve sifreleme turunu listeler.\nRF ortamini haritalamak ve acik ya\nda zayif aglari gormek icin.\nPasif kesif - sadece beacon okur.\nSavunma: tum aglari WPA2/WPA3 ile\nkoru, acik veya WEP birakma."];

pub const WIFI_ANALYZE: Msg = ["Same scan as a 2.4GHz histogram.\nShows AP count per channel 1-13.\nUse it to find crowded channels\nand pick a clear one.\nChannels 1/6/11 do not overlap.\nPassive - no packets are sent.\nDefense: spacing APs on 1/6/11\ncuts interference, not an attack.", "Ayni tarama 2.4GHz histogrami.\nKanal 1-13 basina AP sayisi.\nKalabalik kanallari bulup bos bir\nkanal secmek icin kullanilir.\nKanal 1/6/11 birbiriyle cakismaz.\nPasif - hicbir paket gonderilmez.\nSavunma: AP leri 1/6/11 e yaymak\nparaziti azaltir, saldiri degildir."];

pub const BLE_SCAN: Msg = ["Passively lists nearby BLE devices.\nShows MAC address, RSSI, and name.\nUse it to inventory wearables, tags,\nbeacons and find unknown emitters.\nListen only - it does not connect.\nDefense: devices leak presence;\nuse random MACs and turn BLE off\nwhen it is not needed.", "Yakindaki BLE cihazlarini listeler.\nMAC adresi, RSSI ve adi gosterir.\nGiyilebilir, etiket, beacon saymak\nve bilinmeyen yayinci bulmak icin.\nSadece dinler - baglanmaz.\nSavunma: cihazlar varligi sizdirir;\nrastgele MAC kullan, gereksizse\nBLE yi kapat."];

pub const DETECTOR: Msg = ["Listens for deauth/disassoc frames.\nDetects a deauth ATTACK happening\nnearby in promiscuous mode.\nUse it to catch jamming or forced\ndisconnects of Wi-Fi clients.\nPurely defensive - sends nothing.\nDefense: a spike means someone is\nattacking; enable 802.11w (PMF).", "Deauth/disassoc cercevelerini dinler.\nYakinda olan bir deauth SALDIRISINI\npromiscuous modda tespit eder.\nIstemcilerin zorla kopmasini veya\njamming i yakalamak icin kullanilir.\nTamamen savunmaci - bir sey yollamaz.\nSavunma: ani artis biri saldiriyor\ndemek; 802.11w (PMF) etkinlestir."];

pub const BEACON: Msg = ["Floods fake Wi-Fi beacon frames.\nDozens of bogus access points appear\nin everyone's nearby Wi-Fi list.\nSSID names can be set or random.\nUse: demo how SSID lists are spoofed\nand how easily scanners are tricked.\nDefense: 802.11w / WIDS flags floods.", "Sahte Wi-Fi beacon paketleri yayar.\nHerkesin listesinde onlarca sahte\nerisim noktasi gorunur.\nSSID adlari ayarli ya da rastgele.\nKullanim: SSID sahtekarligini ve\ntarayici aldatmasini gostermek.\nSavunma: 802.11w / WIDS tespit eder."];

pub const PROBE: Msg = ["Sends many fake 802.11 probe reqs.\nMimics phantom clients seeking nets.\nVery noisy; pollutes air monitoring.\nUse: show how probe data is faked\nand how it hides device tracking.\nDefense: rate-limit probes, watch\nfor random MAC bursts.", "Cok sayida sahte probe istegi yollar.\nAg arayan hayalet istemci taklit eder.\nCok gurultulu; izlemeyi kirletir.\nKullanim: probe verisinin nasil sahte\nyapildigini ve takibi gizledigini.\nSavunma: probe limitle, rastgele MAC\npatlamalarini izle."];

pub const BLE_SPAM: Msg = ["Spams BLE advertising packets.\nTriggers pairing popups: Apple, Swift\nPair (Windows), Fast Pair (Android),\nor a flood of junk device names.\nUse: show how BLE ads cause popup\nspam and annoyance attacks.\nDefense: turn off BT in crowds; OS\npatches limit forced popups.", "BLE reklam paketleri yayar.\nEslesme pencereleri tetikler: Apple,\nSwift Pair (Windows), Fast Pair\n(Android) ya da cop isim seli.\nKullanim: BLE reklamlarinin popup\nseli yapisini gostermek.\nSavunma: kalabalikta BT kapat;\nOS yamalari popupu sinirlar."];

pub const EVIL_TWIN: Msg = ["Clones a target SSID as a 2.4GHz WPA2\nrogue AP. A client that tries to join\nreveals EAPOL msg2 -- a MIC keyed to\nthe REAL password -- which we crack\noffline. No deauth, no 5GHz problem.\nDefense: WPA3/PMF, verify BSSID; a\nWIDS spots rogue twin BSSIDs.", "Hedef SSID'yi 2.4GHz WPA2 sahte AP\nolarak klonlar. Baglanmaya calisan\nistemci EAPOL msg2'yi sizdirir -- gercek\nparoladan turemis bir MIC -- onu ofline\nkiririz. Deauth yok, 5GHz sorunu yok.\nSavunma: WPA3/PMF, BSSID dogrula; WIDS\nsahte ikiz BSSID'leri bulur."];

pub const DEAUTH: Msg = ["Sends 802.11 deauth frames to an AP.\nA Wi-Fi denial-of-service attack.\nNOTE: this ESP32 IDF blob REJECTS raw\ndeauth TX, so it is non-functional\nhere -- use Handshake Capture or\nEvil Twin to grab a 4-way instead.\nDefense: enable 802.11w (PMF).", "AP'ye 802.11 deauth cercevesi yollar.\nBir Wi-Fi hizmet engelleme saldirisi.\nNOT: bu ESP32 IDF blob'u ham deauth\nTX'i REDDEDIYOR, burada calismaz --\n4-way icin Handshake Capture veya\nEvil Twin kullan.\nSavunma: 802.11w (PMF) ac."];

pub const HANDSHAKE: Msg = ["Deauths a target so clients reconnect,\nthen sniffs the WPA 4-way handshake\n(EAPOL) during the reconnect.\nThat capture is cracked offline to\nrecover the Wi-Fi password.\nUse: show why weak passphrases fall.\nDefense: long random passphrase\nor WPA3 to resist cracking.", "Hedefi deauth eder, istemci yeniden\nbaglanirken WPA 4-yollu handshake\n(EAPOL) yakalanir.\nBu kayit cevrimdisi kirilarak Wi-Fi\nparolasi elde edilir.\nKullanim: zayif parolanin nasil\ndustugunu gostermek.\nSavunma: uzun rasgele parola / WPA3."];

pub const PORTAL: Msg = ["Runs a fake open AP with DHCP plus a\nDNS hijack: every site redirects to\none fake login page.\nWhatever the victim types is captured.\nUse: phishing / captive-portal demo.\nDefense: check HTTPS + SSID, never\nenter creds on open Wi-Fi.", "Sahte acik AP + DHCP + DNS yonlendirme:\nher site tek bir sahte giris\nsayfasina gider.\nKurbanin yazdigi her sey yakalanir.\nKullanim: oltalama / portal demosu.\nSavunma: HTTPS + SSID dogrula, acik\nWi-Fi'de parola girme."];

pub const NETSCAN: Msg = ["Joins an open Wi-Fi, pulls a DHCP\nlease, then TCP connect-scans the\ngateway/router's common ports.\nFinds exposed services on the LAN.\nUse: map a network's surface.\nDefense: close unused ports, firewall\nand patch the router.", "Acik Wi-Fi'ye baglanir, DHCP alir,\nsonra gateway/router'in yaygin\nportlarini TCP ile tarar.\nLAN'daki acik servisleri bulur.\nKullanim: ag yuzeyini haritalamak.\nSavunma: kullanilmayan portu kapat,\nrouter'a guvenlik duvari + yama."];

pub const CAMSCAN: Msg = ["Joins an open Wi-Fi, sweeps the /24\nfor HTTP hosts (port 80/8080) and\nfingerprints each: Server header +\nauth realm => likely camera/DVR.\nOn a Basic 401 it then tries common\ndefault passwords (admin:admin ...).\nUse: find + audit cameras.\nDefense: change default creds, put\ncameras on a segregated VLAN.", "Acik Wi-Fi'ye baglanir, /24 agini\nHTTP host icin tarar (port 80/8080)\nve parmak izler: Server + auth realm\n=> olasi kamera/DVR. Basic 401 ise\nyaygin varsayilan sifreleri dener\n(admin:admin ...).\nKullanim: kamera bul + denetle.\nSavunma: varsayilan sifreyi degistir,\nkameralari ayri VLAN'a al."];
